### ISSUE TITLE
None of the following assemblies found: 'System.Data.SQLite', 'Microsoft.Data.Sqlite'. At least one is required.

### ISSUE THREAD

**Issue by jjcolumb** [unoplatform/Uno.sqlite-wasm#12]
I have a UNO project using SQLite and it works great in UWP but when trying on web assembly I get this error:

`Error: System.TypeLoadException: None of the following assemblies found: 'System.Data.SQLite', 'Microsoft.Data.Sqlite'. At least one is required`

I installed the Uno.sqlite-wasm nuget into the wasm project.

I am missing any steps? I did not find a nuget for Uno.SQLiteNet

**Comment by jeromelaban** [comment]
Thanks for the report! Can you provide a sample that does not work ?

**Comment by jjcolumb** [comment]
Sorry the delay. Here is with EF https://github.com/jjcolumb/UnoEFDemo
And here is with DevExpress XPO ORM https://github.com/jjcolumb/UnoXpoDemo
Thanks a lot in advance

**Comment by jjcolumb** [comment]
https://sqliteefcore-wasm.platform.uno/ Is the code for this app open source?

**Comment by jeromelaban** [comment]
You can now use this sample: https://github.com/unoplatform/Uno.Samples/tree/master/UI/SQLiteSample

<blockquote><img src="https://avatars1.githubusercontent.com/u/52228309?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/unoplatform/Uno.Samples">unoplatform/Uno.Samples</a></strong></div><div>A collection of code samples for the Uno Platform. Contribute to unoplatform/Uno.Samples development by creating an account on GitHub.</div></blockquote>
