### ISSUE TITLE
Failed to generate AOT layout…

### ISSUE THREAD

**Issue by Daoting** [unoplatform/Uno.sqlite-wasm#14]
Let me talk about the process of referencing the package.
Add the bitcode file e_sqlite3.a as a content to the wasm project. It cannot be built in debug interpreter mode. It always prompts the error of ShellTask.cs in Uno.Wasm.Bootstrap: "Failed to generate AOT layout...", rename e_sqlite3.a to e_sqlite3.bc, the build is successful.
After referencing the package Microsoft.Data.Sqlite, the above error was still reported during the build. In the end, I found out that the P/Invoke method in the sqlitepclraw.provider.e_sqlite3 package does not exist in the exported_functions.json, and the package Microsoft.Data.Sqlite's all versions are reported wrong.
It took several days, I don’t know what to do next, I can only ask you for help. Thank you very much.

**Comment by jeromelaban** [comment]
You can now use this updated sample: https://github.com/unoplatform/Uno.Samples/tree/master/UI/SQLiteSample

<blockquote><img src="https://avatars1.githubusercontent.com/u/52228309?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/unoplatform/Uno.Samples">unoplatform/Uno.Samples</a></strong></div><div>A collection of code samples for the Uno Platform. Contribute to unoplatform/Uno.Samples development by creating an account on GitHub.</div></blockquote>

**Comment by Daoting** [comment]
Thanks
